; ===================================================
;  User-configurable settings
;  Only items listed below can be modified.
;  Omitted entries will use program defaults.
;
;  IMPORTANT: For [file] section, provide only the
;  file name, NOT the full path. The application
;  will locate them in its resource directory.
;  Multiple files should be separated by commas.
; ===================================================

; Enable debug mode. (Open the debug interfac)
debug = false

[file]
; Logging configuration file name
log_conf_file = logging.conf
; Album database file name
album_db_file = album.db
; QSS stylesheet file(s), comma-separated for multiple
qss_files = main_window.qss,
; Icon files, can use '*' to match all files
icon_files = *.svg

[ui]
; User interface mode: "gui" or "cli"
ui = GUI
; Theme name (matches a subdirectory under resources)
theme = default
; Default GUI window size (width,height)
default_window_size = 800,600
; Default TUI terminal size (columns,rows)
default_tui_size = 80,24
; Enable system rounded corners (Windows 11 only)
use_system_round_corners = false
